// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// grp_cpp
IntegerVector grp_cpp(List graph, IntegerVector v, IntegerVector dir);
RcppExport SEXP _MixedGraphs_grp_cpp(SEXP graphSEXP, SEXP vSEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type graph(graphSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(grp_cpp(graph, v, dir));
    return rcpp_result_gen;
END_RCPP
}
// groups_cpp
List groups_cpp(List graph);
RcppExport SEXP _MixedGraphs_groups_cpp(SEXP graphSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type graph(graphSEXP);
    rcpp_result_gen = Rcpp::wrap(groups_cpp(graph));
    return rcpp_result_gen;
END_RCPP
}
// adj_cpp
IntegerVector adj_cpp(List graph, IntegerVector v, IntegerVector dir);
RcppExport SEXP _MixedGraphs_adj_cpp(SEXP graphSEXP, SEXP vSEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type graph(graphSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_cpp(graph, v, dir));
    return rcpp_result_gen;
END_RCPP
}
// adjMat_to_adjList
List adjMat_to_adjList(NumericMatrix aM);
RcppExport SEXP _MixedGraphs_adjMat_to_adjList(SEXP aMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type aM(aMSEXP);
    rcpp_result_gen = Rcpp::wrap(adjMat_to_adjList(aM));
    return rcpp_result_gen;
END_RCPP
}
// rev_adjList_cpp
List rev_adjList_cpp(List adjList);
RcppExport SEXP _MixedGraphs_rev_adjList_cpp(SEXP adjListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adjList(adjListSEXP);
    rcpp_result_gen = Rcpp::wrap(rev_adjList_cpp(adjList));
    return rcpp_result_gen;
END_RCPP
}
// sym_adjList_cpp
List sym_adjList_cpp(List adjList);
RcppExport SEXP _MixedGraphs_sym_adjList_cpp(SEXP adjListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adjList(adjListSEXP);
    rcpp_result_gen = Rcpp::wrap(sym_adjList_cpp(adjList));
    return rcpp_result_gen;
END_RCPP
}
// match_char
IntegerVector match_char(CharacterVector x, CharacterVector y);
RcppExport SEXP _MixedGraphs_match_char(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(match_char(x, y));
    return rcpp_result_gen;
END_RCPP
}
// match_
IntegerVector match_(NumericVector x, NumericVector y);
RcppExport SEXP _MixedGraphs_match_(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(match_(x, y));
    return rcpp_result_gen;
END_RCPP
}
// add_edges_aM
NumericMatrix add_edges_aM(NumericMatrix aM, IntegerVector e1, IntegerVector e2, int dir);
RcppExport SEXP _MixedGraphs_add_edges_aM(SEXP aMSEXP, SEXP e1SEXP, SEXP e2SEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type aM(aMSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e2(e2SEXP);
    Rcpp::traits::input_parameter< int >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(add_edges_aM(aM, e1, e2, dir));
    return rcpp_result_gen;
END_RCPP
}
// add_edges_aL
List add_edges_aL(List aL, IntegerVector e1, IntegerVector e2, int dir);
RcppExport SEXP _MixedGraphs_add_edges_aL(SEXP aLSEXP, SEXP e1SEXP, SEXP e2SEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type aL(aLSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e2(e2SEXP);
    Rcpp::traits::input_parameter< int >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(add_edges_aL(aL, e1, e2, dir));
    return rcpp_result_gen;
END_RCPP
}
// rmv_edges_aL
List rmv_edges_aL(List aL, IntegerVector e1, IntegerVector e2, int dir);
RcppExport SEXP _MixedGraphs_rmv_edges_aL(SEXP aLSEXP, SEXP e1SEXP, SEXP e2SEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type aL(aLSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e2(e2SEXP);
    Rcpp::traits::input_parameter< int >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(rmv_edges_aL(aL, e1, e2, dir));
    return rcpp_result_gen;
END_RCPP
}
// rmv_edges_aM
NumericMatrix rmv_edges_aM(NumericMatrix aM, IntegerVector e1, IntegerVector e2, int dir);
RcppExport SEXP _MixedGraphs_rmv_edges_aM(SEXP aMSEXP, SEXP e1SEXP, SEXP e2SEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type aM(aMSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e2(e2SEXP);
    Rcpp::traits::input_parameter< int >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(rmv_edges_aM(aM, e1, e2, dir));
    return rcpp_result_gen;
END_RCPP
}
// chg_ends_cpp
List chg_ends_cpp(NumericMatrix m1, NumericMatrix m2, NumericVector v1, NumericVector v2, bool d2);
RcppExport SEXP _MixedGraphs_chg_ends_cpp(SEXP m1SEXP, SEXP m2SEXP, SEXP v1SEXP, SEXP v2SEXP, SEXP d2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m2(m2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< bool >::type d2(d2SEXP);
    rcpp_result_gen = Rcpp::wrap(chg_ends_cpp(m1, m2, v1, v2, d2));
    return rcpp_result_gen;
END_RCPP
}
// complete_mg_cpp
List complete_mg_cpp(IntegerVector n, IntegerVector m);
RcppExport SEXP _MixedGraphs_complete_mg_cpp(SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(complete_mg_cpp(n, m));
    return rcpp_result_gen;
END_RCPP
}
// complete_gr_cpp
List complete_gr_cpp(IntegerVector n, LogicalVector dir);
RcppExport SEXP _MixedGraphs_complete_gr_cpp(SEXP nSEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(complete_gr_cpp(n, dir));
    return rcpp_result_gen;
END_RCPP
}
// chain_gr_cpp
List chain_gr_cpp(IntegerVector n, LogicalVector dir);
RcppExport SEXP _MixedGraphs_chain_gr_cpp(SEXP nSEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(chain_gr_cpp(n, dir));
    return rcpp_result_gen;
END_RCPP
}
// cycle_gr_cpp
List cycle_gr_cpp(int n, LogicalVector dir);
RcppExport SEXP _MixedGraphs_cycle_gr_cpp(SEXP nSEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(cycle_gr_cpp(n, dir));
    return rcpp_result_gen;
END_RCPP
}
// bipartite_gr_cpp
List bipartite_gr_cpp(int n, int m, LogicalVector dir);
RcppExport SEXP _MixedGraphs_bipartite_gr_cpp(SEXP nSEXP, SEXP mSEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(bipartite_gr_cpp(n, m, dir));
    return rcpp_result_gen;
END_RCPP
}
// grid_gr_cpp
List grid_gr_cpp(int n, int m, LogicalVector dir);
RcppExport SEXP _MixedGraphs_grid_gr_cpp(SEXP nSEXP, SEXP mSEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(grid_gr_cpp(n, m, dir));
    return rcpp_result_gen;
END_RCPP
}
// star_gr_cpp
List star_gr_cpp(int n, LogicalVector dir, int cn);
RcppExport SEXP _MixedGraphs_star_gr_cpp(SEXP nSEXP, SEXP dirSEXP, SEXP cnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type dir(dirSEXP);
    Rcpp::traits::input_parameter< int >::type cn(cnSEXP);
    rcpp_result_gen = Rcpp::wrap(star_gr_cpp(n, dir, cn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MixedGraphs_grp_cpp", (DL_FUNC) &_MixedGraphs_grp_cpp, 3},
    {"_MixedGraphs_groups_cpp", (DL_FUNC) &_MixedGraphs_groups_cpp, 1},
    {"_MixedGraphs_adj_cpp", (DL_FUNC) &_MixedGraphs_adj_cpp, 3},
    {"_MixedGraphs_adjMat_to_adjList", (DL_FUNC) &_MixedGraphs_adjMat_to_adjList, 1},
    {"_MixedGraphs_rev_adjList_cpp", (DL_FUNC) &_MixedGraphs_rev_adjList_cpp, 1},
    {"_MixedGraphs_sym_adjList_cpp", (DL_FUNC) &_MixedGraphs_sym_adjList_cpp, 1},
    {"_MixedGraphs_match_char", (DL_FUNC) &_MixedGraphs_match_char, 2},
    {"_MixedGraphs_match_", (DL_FUNC) &_MixedGraphs_match_, 2},
    {"_MixedGraphs_add_edges_aM", (DL_FUNC) &_MixedGraphs_add_edges_aM, 4},
    {"_MixedGraphs_add_edges_aL", (DL_FUNC) &_MixedGraphs_add_edges_aL, 4},
    {"_MixedGraphs_rmv_edges_aL", (DL_FUNC) &_MixedGraphs_rmv_edges_aL, 4},
    {"_MixedGraphs_rmv_edges_aM", (DL_FUNC) &_MixedGraphs_rmv_edges_aM, 4},
    {"_MixedGraphs_chg_ends_cpp", (DL_FUNC) &_MixedGraphs_chg_ends_cpp, 5},
    {"_MixedGraphs_complete_mg_cpp", (DL_FUNC) &_MixedGraphs_complete_mg_cpp, 2},
    {"_MixedGraphs_complete_gr_cpp", (DL_FUNC) &_MixedGraphs_complete_gr_cpp, 2},
    {"_MixedGraphs_chain_gr_cpp", (DL_FUNC) &_MixedGraphs_chain_gr_cpp, 2},
    {"_MixedGraphs_cycle_gr_cpp", (DL_FUNC) &_MixedGraphs_cycle_gr_cpp, 2},
    {"_MixedGraphs_bipartite_gr_cpp", (DL_FUNC) &_MixedGraphs_bipartite_gr_cpp, 3},
    {"_MixedGraphs_grid_gr_cpp", (DL_FUNC) &_MixedGraphs_grid_gr_cpp, 3},
    {"_MixedGraphs_star_gr_cpp", (DL_FUNC) &_MixedGraphs_star_gr_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_MixedGraphs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
