// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// grp_cpp
IntegerVector grp_cpp(List graph, IntegerVector v, int dir);
RcppExport SEXP _MixedGraphs_grp_cpp(SEXP graphSEXP, SEXP vSEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type graph(graphSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(grp_cpp(graph, v, dir));
    return rcpp_result_gen;
END_RCPP
}
// adj_cpp
IntegerVector adj_cpp(List graph, IntegerVector v, int dir);
RcppExport SEXP _MixedGraphs_adj_cpp(SEXP graphSEXP, SEXP vSEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type graph(graphSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_cpp(graph, v, dir));
    return rcpp_result_gen;
END_RCPP
}
// adjMat_to_adjList
List adjMat_to_adjList(NumericMatrix aM);
RcppExport SEXP _MixedGraphs_adjMat_to_adjList(SEXP aMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type aM(aMSEXP);
    rcpp_result_gen = Rcpp::wrap(adjMat_to_adjList(aM));
    return rcpp_result_gen;
END_RCPP
}
// rev_adjList_cpp
List rev_adjList_cpp(List adjList);
RcppExport SEXP _MixedGraphs_rev_adjList_cpp(SEXP adjListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adjList(adjListSEXP);
    rcpp_result_gen = Rcpp::wrap(rev_adjList_cpp(adjList));
    return rcpp_result_gen;
END_RCPP
}
// sym_adjList_cpp
List sym_adjList_cpp(List adjList);
RcppExport SEXP _MixedGraphs_sym_adjList_cpp(SEXP adjListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adjList(adjListSEXP);
    rcpp_result_gen = Rcpp::wrap(sym_adjList_cpp(adjList));
    return rcpp_result_gen;
END_RCPP
}
// add_edges_aM
NumericMatrix add_edges_aM(NumericMatrix aM, IntegerVector e1, IntegerVector e2, int dir);
RcppExport SEXP _MixedGraphs_add_edges_aM(SEXP aMSEXP, SEXP e1SEXP, SEXP e2SEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type aM(aMSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e2(e2SEXP);
    Rcpp::traits::input_parameter< int >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(add_edges_aM(aM, e1, e2, dir));
    return rcpp_result_gen;
END_RCPP
}
// add_edges_aL
List add_edges_aL(List aL, IntegerVector e1, IntegerVector e2, int dir);
RcppExport SEXP _MixedGraphs_add_edges_aL(SEXP aLSEXP, SEXP e1SEXP, SEXP e2SEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type aL(aLSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e2(e2SEXP);
    Rcpp::traits::input_parameter< int >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(add_edges_aL(aL, e1, e2, dir));
    return rcpp_result_gen;
END_RCPP
}
// rmv_edges_aL
List rmv_edges_aL(List aL, IntegerVector e1, IntegerVector e2, int dir);
RcppExport SEXP _MixedGraphs_rmv_edges_aL(SEXP aLSEXP, SEXP e1SEXP, SEXP e2SEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type aL(aLSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e2(e2SEXP);
    Rcpp::traits::input_parameter< int >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(rmv_edges_aL(aL, e1, e2, dir));
    return rcpp_result_gen;
END_RCPP
}
// rmv_edges_aM
NumericMatrix rmv_edges_aM(NumericMatrix aM, IntegerVector e1, IntegerVector e2, int dir);
RcppExport SEXP _MixedGraphs_rmv_edges_aM(SEXP aMSEXP, SEXP e1SEXP, SEXP e2SEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type aM(aMSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type e2(e2SEXP);
    Rcpp::traits::input_parameter< int >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(rmv_edges_aM(aM, e1, e2, dir));
    return rcpp_result_gen;
END_RCPP
}
// chg_ends_cpp
List chg_ends_cpp(NumericMatrix m1, NumericMatrix m2, NumericVector v1, NumericVector v2, bool d2);
RcppExport SEXP _MixedGraphs_chg_ends_cpp(SEXP m1SEXP, SEXP m2SEXP, SEXP v1SEXP, SEXP v2SEXP, SEXP d2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m2(m2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< bool >::type d2(d2SEXP);
    rcpp_result_gen = Rcpp::wrap(chg_ends_cpp(m1, m2, v1, v2, d2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MixedGraphs_grp_cpp", (DL_FUNC) &_MixedGraphs_grp_cpp, 3},
    {"_MixedGraphs_adj_cpp", (DL_FUNC) &_MixedGraphs_adj_cpp, 3},
    {"_MixedGraphs_adjMat_to_adjList", (DL_FUNC) &_MixedGraphs_adjMat_to_adjList, 1},
    {"_MixedGraphs_rev_adjList_cpp", (DL_FUNC) &_MixedGraphs_rev_adjList_cpp, 1},
    {"_MixedGraphs_sym_adjList_cpp", (DL_FUNC) &_MixedGraphs_sym_adjList_cpp, 1},
    {"_MixedGraphs_add_edges_aM", (DL_FUNC) &_MixedGraphs_add_edges_aM, 4},
    {"_MixedGraphs_add_edges_aL", (DL_FUNC) &_MixedGraphs_add_edges_aL, 4},
    {"_MixedGraphs_rmv_edges_aL", (DL_FUNC) &_MixedGraphs_rmv_edges_aL, 4},
    {"_MixedGraphs_rmv_edges_aM", (DL_FUNC) &_MixedGraphs_rmv_edges_aM, 4},
    {"_MixedGraphs_chg_ends_cpp", (DL_FUNC) &_MixedGraphs_chg_ends_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_MixedGraphs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
