// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// grp_cpp
IntegerVector grp_cpp(List graph, IntegerVector v, int dir);
RcppExport SEXP _MixedGraphs_grp_cpp(SEXP graphSEXP, SEXP vSEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type graph(graphSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(grp_cpp(graph, v, dir));
    return rcpp_result_gen;
END_RCPP
}
// adjMat_to_adjList
List adjMat_to_adjList(NumericMatrix aM);
RcppExport SEXP _MixedGraphs_adjMat_to_adjList(SEXP aMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type aM(aMSEXP);
    rcpp_result_gen = Rcpp::wrap(adjMat_to_adjList(aM));
    return rcpp_result_gen;
END_RCPP
}
// rev_adjList_cpp
List rev_adjList_cpp(List adjList);
RcppExport SEXP _MixedGraphs_rev_adjList_cpp(SEXP adjListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adjList(adjListSEXP);
    rcpp_result_gen = Rcpp::wrap(rev_adjList_cpp(adjList));
    return rcpp_result_gen;
END_RCPP
}
// sym_adjList_cpp
List sym_adjList_cpp(List adjList);
RcppExport SEXP _MixedGraphs_sym_adjList_cpp(SEXP adjListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adjList(adjListSEXP);
    rcpp_result_gen = Rcpp::wrap(sym_adjList_cpp(adjList));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MixedGraphs_grp_cpp", (DL_FUNC) &_MixedGraphs_grp_cpp, 3},
    {"_MixedGraphs_adjMat_to_adjList", (DL_FUNC) &_MixedGraphs_adjMat_to_adjList, 1},
    {"_MixedGraphs_rev_adjList_cpp", (DL_FUNC) &_MixedGraphs_rev_adjList_cpp, 1},
    {"_MixedGraphs_sym_adjList_cpp", (DL_FUNC) &_MixedGraphs_sym_adjList_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_MixedGraphs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
