# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grp_cpp <- function(graph, v, dir) {
    .Call('_MixedGraphs_grp_cpp', PACKAGE = 'MixedGraphs', graph, v, dir)
}

adjMat_to_adjList <- function(aM) {
    .Call('_MixedGraphs_adjMat_to_adjList', PACKAGE = 'MixedGraphs', aM)
}

rev_adjList_cpp <- function(adjList) {
    .Call('_MixedGraphs_rev_adjList_cpp', PACKAGE = 'MixedGraphs', adjList)
}

sym_adjList_cpp <- function(adjList) {
    .Call('_MixedGraphs_sym_adjList_cpp', PACKAGE = 'MixedGraphs', adjList)
}

add_edges_aM <- function(aM, e1, e2, dir) {
    .Call('_MixedGraphs_add_edges_aM', PACKAGE = 'MixedGraphs', aM, e1, e2, dir)
}

add_edges_aL <- function(aL, e1, e2, dir) {
    .Call('_MixedGraphs_add_edges_aL', PACKAGE = 'MixedGraphs', aL, e1, e2, dir)
}

rmv_edges_aL <- function(aL, e1, e2, dir) {
    .Call('_MixedGraphs_rmv_edges_aL', PACKAGE = 'MixedGraphs', aL, e1, e2, dir)
}

rmv_edges_aM <- function(aM, e1, e2, dir) {
    .Call('_MixedGraphs_rmv_edges_aM', PACKAGE = 'MixedGraphs', aM, e1, e2, dir)
}

